"""Developer tool (not needed to build or run StrataHome): regenerates the UI assets that are committed.

  assets/fonts/Outfit-{Regular,Medium,Bold,Black}.ttf   static instances of Strata's bundled variable Outfit font
  assets/fonts/OFL.txt                                   its licence (SIL OFL 1.1), copied alongside
  src/Ui/IconData.g.cs                                   the icon geometry, from Strata's sprite.svg

Usage:  python tools/make_ui_assets.py "<Strata folder>\\serve\\web"
Needs:  pip install fonttools brotli
"""
import os
import shutil
import sys
import xml.etree.ElementTree as ET

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

web = sys.argv[1]
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
fonts = os.path.join(root, "assets", "fonts")
os.makedirs(fonts, exist_ok=True)

# ---- fonts: WPF cannot read woff2 or variable axes, so cut the four weights the web app uses
src = os.path.join(web, "fonts", "outfit-latin-wght.woff2")
for name, weight in (("Regular", 400), ("Medium", 500), ("Bold", 700), ("Black", 900)):
    inst = instancer.instantiateVariableFont(TTFont(src), {"wght": weight}, inplace=False, updateFontNames=True)
    inst.flavor = None
    # name the faces the way WPF groups them: Regular + Bold share the family "Outfit"; Medium and Black are families of
    # their own ("Outfit Medium", "Outfit Black"), each with one Regular face. No typographic (16/17) names.
    family = "Outfit" if name in ("Regular", "Bold") else "Outfit " + name
    style = "Bold" if name == "Bold" else "Regular"
    n = inst["name"]
    for nid in (16, 17, 21, 22, 25):
        n.removeNames(nameID=nid)
    for nid, value in ((1, family), (2, style), (3, "Outfit-%s;strata-ui" % name), (4, family if style == "Regular" else family + " Bold"),
                       (6, "Outfit-" + name)):
        n.setName(value, nid, 3, 1, 0x409)
        n.setName(value, nid, 1, 0, 0)
    inst["OS/2"].fsSelection = (inst["OS/2"].fsSelection & ~0b1100001) | (0b100000 if style == "Bold" else 0b1000000)
    inst["head"].macStyle = 1 if style == "Bold" else 0
    out = os.path.join(fonts, "Outfit-%s.ttf" % name)
    inst.save(out)
    n = inst["name"]
    print("%-12s %6d bytes  family=%r subfamily=%r typographic=%r/%r" % (
        os.path.basename(out), os.path.getsize(out), n.getDebugName(1), n.getDebugName(2), n.getDebugName(16), n.getDebugName(17)))
shutil.copy(os.path.join(web, "fonts", "OFL.txt"), os.path.join(fonts, "OFL.txt"))

# ---- icons: every symbol is plain <path> elements, a 12% fill layer plus 1.5-wide strokes
ns = "{http://www.w3.org/2000/svg}"
lines = [
    "// <auto-generated> by tools/make_ui_assets.py from Strata's web/sprite.svg. Do not edit by hand. </auto-generated>",
    "using System.Collections.Generic;",
    "",
    "namespace StrataHome",
    "{",
    "    internal static class IconData",
    "    {",
    "        /// <summary>name -> { fill paths (drawn at 12% opacity), stroke paths (1.5 wide, round caps and joins) }, 24 x 24.</summary>",
    "        public static readonly Dictionary<string, string[][]> All = new Dictionary<string, string[][]>",
    "        {",
]
count = 0
for sym in ET.parse(os.path.join(web, "sprite.svg")).getroot().iter(ns + "symbol"):
    fills, strokes = [], []
    for e in sym:
        (fills if e.attrib.get("opacity") else strokes).append(e.attrib["d"])
    name = sym.attrib["id"].replace("i-", "")
    q = lambda xs: "new string[] { " + ", ".join('"%s"' % x for x in xs) + " }"
    lines.append('            { "%s", new string[][] { %s, %s } },' % (name, q(fills), q(strokes)))
    count += 1
lines += ["        };", "    }", "}", ""]
os.makedirs(os.path.join(root, "src", "Ui"), exist_ok=True)
with open(os.path.join(root, "src", "Ui", "IconData.g.cs"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print("wrote src/Ui/IconData.g.cs with %d icons" % count)
